# Generated by Django 5.0 on 2025-03-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_user',
            new_name='tbl_customer',
        ),
    ]
