# Generated by Django 5.1.7 on 2025-03-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_tbl_user_tbl_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_customer',
            old_name='First_name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='Last_name',
        ),
        migrations.RemoveField(
            model_name='tbl_customer',
            name='Username',
        ),
    ]
