# Generated by Django 5.1.7 on 2025-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_first_name_tbl_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('Course', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_customer',
        ),
    ]
